CHECK_APT_ERROR---EOL---
<class 'apt_pkg.Error'>
Error: E:Malformed line 1 in source list /etc/apt/sources.list (type), E:The list of sources could not be read.
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/checkAPT.py", line 355, in <module>
    check = APTCheck()
  File "/usr/lib/linuxmint/mintUpdate/checkAPT.py", line 26, in __init__
    self.cache = apt.Cache()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 170, in __init__
    self.open(progress)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 232, in open
    self._cache = apt_pkg.Cache(progress)
apt_pkg.Error: E:Malformed line 1 in source list /etc/apt/sources.list (type), E:The list of sources could not be read.
E:Malformed line 1 in source list /etc/apt/sources.list (type), E:The list of sources could not be read.
